/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://5szbthmawvfxxnv7tm4jrgkcti.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-x5fqw3l7cnb2nnb6noriy4qomu",
    "aws_cognito_identity_pool_id": "us-east-2:5ab18641-43b6-4971-aac6-3b5866e79ea8",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_5b59DuwWc",
    "aws_user_pools_web_client_id": "3skkhof25h7sdaual6493plm96",
    "oauth": {},
    "aws_user_files_s3_bucket": "naturamaoli184309-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
